DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS sessions;

DROP TABLE IF EXISTS accounts;

DROP TABLE IF EXISTS posts;

DROP TABLE IF EXISTS likes;

DROP TABLE IF EXISTS txs;

DROP TABLE IF EXISTS tags;

DROP TABLE IF EXISTS tags_to_targets;

DROP TABLE IF EXISTS scheduled_tasks;

DROP TABLE IF EXISTS batches;

DROP TABLE IF EXISTS items;

DROP TABLE IF EXISTS marketing_campaigns;

DROP TABLE IF EXISTS currencies;

DROP TABLE IF EXISTS balances;

DROP TABLE IF EXISTS positions;

DROP TABLE IF EXISTS wallets;

DROP TABLE IF EXISTS short_options;

DROP TABLE IF EXISTS emission;

